version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: blockchain
      POSTGRES_PASSWORD: myPassword243OSOKpadpa
      POSTGRES_DB: blockchain_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bitcoin-wallet:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
