server:
  port: ${PORT:9001}
  servlet:
    context-path: /api/bitcoin

spring:
  application:
    name: Bitcoin Wallet Service - Development
  datasource:
    url: jdbc:postgresql://postgres:5432/blockchain_db
    username: blockchain
    password: myPassword243OSOKpadpa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

bitcoin:
  network: org.bitcoin.production
  targetNode: seed.bitcoin.sipa.be
  port: 8080

logging:
  level:
    springframework: WARN
    org.hibernate.sql: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN