server:
  port: 8000
  servlet:
    context-path: /api

spring:
  application:
    name: Bitcoin Wallet Service - Development
  datasource:
    url: jdbc:postgresql://localhost:5432/blockchain_db
    username: blockchain
    password: myPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
bitcoin:
  network: org.bitcoin.production

logging:
  level:
    root: WARN
    springframework: WARN
    org.hibernate.sql: WARN
    org.bitcoinj: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN