server:
  port: 9001
  servlet:
    context-path: /api/bitcoin

spring:
  application:
    name: Bitcoin Wallet Service - Development
  datasource:
    url: jdbc:postgresql://localhost:5432/blockchain_db
    username: blockchain
    password: myPassword243OSOKpadpa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

bitcoin:
  network: org.bitcoin.production

logging:
  level:
    springframework: WARN
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
