server:
  port: ${PORT:9001}
  servlet:
    context-path: /api/bitcoin

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/blockchain_db
    username: blockchain
    password: myPassword243OSOKpadpa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration

bitcoin:
  network: org.bitcoin.production
  targetNode: seed.bitcoin.sipa.be
  port: 8080